
version: "3.9"

services:
  web:
    build: .
#    command: python /code/manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&  python manage.py runserver 0.0.0.0:8000"

    env_file:
      - prod.env
    #   Порты для nginx
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgis/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - prod.env
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  postgres_data: