# Generated by Django 4.1.7 on 2023-04-06 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0002_alter_point_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=3857, verbose_name='Геометрия'),
        ),
    ]
