# Generated by Django 4.1.7 on 2023-04-07 07:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0003_alter_point_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestring',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='point',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857, verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Полигон'),
        ),
    ]
