# Generated by Django 4.1.7 on 2023-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0006_sss'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='polygon',
            field=models.ManyToManyField(to='geo_api.polygon'),
        ),
    ]
