# Generated by Django 4.1.7 on 2023-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0007_point_polygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSS',
        ),
        migrations.AlterField(
            model_name='point',
            name='polygon',
            field=models.ManyToManyField(related_name='points', to='geo_api.polygon'),
        ),
    ]
